In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [6]:
l=pd.read_csv('C:\\Users\\MRUH\\Desktop\\App-dev-main\\loan21.csv')
l

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes          3  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0           0             360.0   
1               3076               1500           0             360.0   
2               5000               1800           0             360.0   
3               2340               2546           0             360.0   
4               3276                  0           0             360.0   
..               ...                ...         ...               ...   
362             4009               1777           1             360.0   
363             4158                709           1             360.0   
364             3250               1993           1             360.0   
365             5000               2393           1             360.0   
366             9200                  0           1             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [7]:
l.shape

(367, 12)

In [8]:
l.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [9]:
def Gender(x):
    if x=='Male':
        return 1
    if x=='Female':
        return 2
def Married(x):
    if x=='Yes':
        return 0
    if x=='No':
        return 1
def Self_Employed(x):
    if x=='Yes':
        return 0
    if x=='No':
        return 1
def Education(x):
    if x=='Graduate':
        return 0
    if x=='Not Graduate':
        return 1
def Dependents(x):
    if x=='3+':
        return 3
    elif x=='1':
        return 1
    else:
        return 2
def Property_Area(x):
    if x=='Urban':
        return 0
    if x=='Semiurban':
        return 1
    if x=='Rural':
        return 2
    

In [10]:
l['Gender']=l['Gender'].apply(Gender)
l['Married']=l['Married'].apply(Married)
l['Education']=l['Education'].apply(Education)
l['Self_Employed']=l['Self_Employed'].apply(Self_Employed)
l['Dependents']=l['Dependents'].apply(Dependents)
l['Property_Area']=l['Property_Area'].apply(Property_Area)

In [11]:
l

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001015     1.0        0           2          0            1.0   
1    LP001022     1.0        0           1          0            1.0   
2    LP001031     1.0        0           2          0            1.0   
3    LP001035     1.0        0           2          0            1.0   
4    LP001051     1.0        1           2          1            1.0   
..        ...     ...      ...         ...        ...            ...   
362  LP002971     1.0        0           2          1            0.0   
363  LP002975     1.0        0           2          0            1.0   
364  LP002980     1.0        1           2          0            1.0   
365  LP002986     1.0        0           2          0            1.0   
366  LP002989     1.0        1           2          0            0.0   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0           0             360.0   
1               3076               1500           0             360.0   
2               5000               1800           0             360.0   
3               2340               2546           0             360.0   
4               3276                  0           0             360.0   
..               ...                ...         ...               ...   
362             4009               1777           1             360.0   
363             4158                709           1             360.0   
364             3250               1993           1             360.0   
365             5000               2393           1             360.0   
366             9200                  0           1             180.0   

     Credit_History  Property_Area  
0               1.0              0  
1               1.0              0  
2               1.0              0  
3               NaN              0  
4               1.0              0  
..              ...            ...  
362             1.0              0  
363             1.0              0  
364             NaN              1  
365             1.0              2  
366             1.0              2  

[367 rows x 12 columns]

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
model= LogisticRegression()

In [14]:
import math
med=math.floor(l.Gender.median())
med1=math.floor(l.Self_Employed.median())
med2=math.floor(l.Credit_History.median())
mea=math.floor(l.LoanAmount.mean())
mea1=math.floor(l.Loan_Amount_Term.mean())
l.Gender=l.Gender.fillna(med)
l.Self_Employed=l.Self_Employed.fillna(med1)
l.LoanAmount=l.LoanAmount.fillna(mea)
l.Loan_Amount_Term =l.Loan_Amount_Term .fillna(mea1)
l.Credit_History =l.Credit_History .fillna(med2)

In [15]:
x=l.drop(['LoanAmount','Loan_ID'],axis='columns')

In [16]:
y=l.LoanAmount

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.3)

In [18]:
model.fit(x_train,y_train)

LogisticRegression()

In [19]:
model.predict([[1,0,2,1,1,5720,0,180,2,1]])

array([0], dtype=int64)

In [20]:
model.predict([[0,1,2,0,0,5,1,190,1,0]])

array([0], dtype=int64)

In [22]:
import pickle
pickle.dump(model, open("reg.pkl", "wb"))

In [23]:
model = pickle.load(open("reg.pkl", "rb"))
model

LogisticRegression()

In [24]:
model.predict([[1,0,2,1,1,5720,0,180,2,1]])

array([0], dtype=int64)